/**
 * Vimeo 视频页提取器，含播放器配置 / 字幕抓取逻辑。
 *
 * 走播放器配置端点：`player.vimeo.com/video/{id}/config`，
 * 返回体的 `request.text_tracks[]` 里带已签名的 `.vtt` 地址，公开视频无需鉴权。
 *
 * 数据流：
 *   GET player.vimeo.com/video/{id}/config
 *     └─ .request.text_tracks[]  { id, lang, url, kind, label }
 *          └─ GET {url}   （captions.vimeo.com，带 expires + sig）
 *               └─ WebVTT 文本
 *
 * 说明：
 * - 官方 REST `/videos/{id}/texttracks` 需要 OAuth token，扩展里用不了，故不采用；
 * - VTT 地址带时效签名（`expires`），不能缓存，必须现取现用；
 * - 实测 captions.vimeo.com 对签名地址返回 `access-control-allow-origin: *`，
 *   因此 content script 跨源取字幕正文没有问题。
 */

import { defaultLogger } from '../../lib/logger';
import { ExtractResult } from '../interfaces';
import { AbstractContentExtractor } from './abstract.extractor';
import { parseVtt } from './utils/vtt';
import { formatVideoMarkdown } from './utils/video-markdown';

const CONFIG_ENDPOINT = 'https://player.vimeo.com/video';

/** `player.vimeo.com/video/{id}/config` 返回体中用到的字段 */
interface VimeoPlayerConfig {
  video?: {
    id: number;
    title: string;
    duration: number;
    owner?: { name?: string };
  };
  request?: {
    text_tracks?: VimeoTextTrack[];
  };
}

interface VimeoTextTrack {
  id: number;
  /** 形如 `en` / `de`；自动生成的字幕为 `en-x-autogen` */
  lang: string;
  /** 已签名的 vtt 地址；老视频可能是 `/texttrack/xxx.vtt?token=` 这样的相对路径 */
  url: string;
  /** `subtitles` / `captions` */
  kind: string;
  /** 人类可读名，如 `English` */
  label: string;
  /** `user_uploaded` 等 */
  provenance?: string;
  default?: boolean;
}

/** 单条字幕，`from` / `to` 单位为秒，与 B 站 / YouTube 结构对齐 */
interface VimeoSubtitleLine {
  content: string;
  from: number;
  to: number;
}

interface VimeoSubtitleTrack {
  languageCode: string;
  label: string;
  /** `lang` 带 `-x-autogen` 后缀即为自动生成 */
  autoGenerated: boolean;
}

interface VimeoVideoData {
  videoId: string;
  title: string;
  author: string;
  /** 播放器配置不下发简介，恒为空串；保留字段是为了与其他站点结构一致 */
  description: string;
  /** 视频时长（秒），拿不到时为 0 */
  duration: number;
  subtitle: VimeoSubtitleLine[];
  /** 实际取到字幕的轨道，未取到时为 null */
  selectedTrack: VimeoSubtitleTrack | null;
  availableTracks: VimeoSubtitleTrack[];
}

interface GetVimeoDataOptions {
  /**
   * 语言偏好，按顺序匹配。支持前缀匹配：`zh` 可命中 `zh-Hans`。
   * 默认 `['zh-Hans', 'zh', 'en']`。
   */
  preferredLanguages?: string[];
  /** 是否接受自动生成字幕（`-x-autogen`）。默认 true，同语言仍优先人工字幕 */
  allowAutoGenerated?: boolean;
  /** 私密视频的 hash（URL 形如 `vimeo.com/{id}/{hash}`），取配置时必须带上 */
  unlistedHash?: string;
}

const DEFAULT_PREFERRED_LANGUAGES = ['zh-Hans', 'zh', 'en'];

/**
 * 从 URL 中解析视频 ID 与私密 hash。
 *
 * 兼容 `vimeo.com/123456`、`vimeo.com/123456/abcdef`（私密链接）、
 * `player.vimeo.com/video/123456`、`vimeo.com/channels/xxx/123456`。
 *
 * @returns 解析失败返回 null
 */
function parseVimeoVideoId(
  rawUrl: string,
): { videoId: string; unlistedHash?: string } | null {
  let url: URL;
  try {
    url = new URL(rawUrl);
  } catch {
    return null;
  }

  if (!/(^|\.)vimeo\.com$/.test(url.hostname)) {
    return null;
  }

  // 路径里第一个纯数字段就是视频 ID，可覆盖 /channels/xxx/123456 之类的嵌套路径
  const segments = url.pathname.split('/').filter(Boolean);
  const index = segments.findIndex((segment) => /^\d+$/.test(segment));
  if (index === -1) {
    return null;
  }

  const videoId = segments[index];
  // 紧跟其后的非数字段是私密视频 hash
  const next = segments[index + 1];
  const unlistedHash =
    next && /^[0-9a-f]+$/i.test(next) && !/^\d+$/.test(next) ? next : undefined;

  const hashFromQuery = url.searchParams.get('h') ?? undefined;

  return { videoId, unlistedHash: unlistedHash ?? hashFromQuery };
}

/**
 * 拉取播放器配置。
 */
async function fetchPlayerConfig(
  videoId: string,
  unlistedHash?: string,
): Promise<VimeoPlayerConfig | null> {
  const suffix = unlistedHash ? `?h=${encodeURIComponent(unlistedHash)}` : '';
  const url = `${CONFIG_ENDPOINT}/${encodeURIComponent(videoId)}/config${suffix}`;
  try {
    const res = await fetch(url, { credentials: 'include' });
    if (!res.ok) {
      // 403 常见于私密视频缺 hash，或域名白名单限制了嵌入
      defaultLogger.warn('[vimeo] config request failed:', res.status);
      return null;
    }
    return (await res.json()) as VimeoPlayerConfig;
  } catch (err) {
    defaultLogger.warn('[vimeo] config request error:', err);
    return null;
  }
}

function isAutoGenerated(track: VimeoTextTrack): boolean {
  return track.lang.toLowerCase().includes('-x-autogen');
}

/** 去掉 `-x-autogen` 后缀，拿到干净的语言码用于匹配 */
function normalizeLang(lang: string): string {
  return lang.toLowerCase().replace(/-x-autogen$/, '');
}

function toTrackInfo(track: VimeoTextTrack): VimeoSubtitleTrack {
  return {
    languageCode: track.lang,
    label: track.label || track.lang,
    autoGenerated: isAutoGenerated(track),
  };
}

/**
 * 按语言偏好挑一条轨道，同语言下人工字幕优先。
 */
function pickTrack(
  tracks: VimeoTextTrack[],
  preferredLanguages: string[],
  allowAutoGenerated: boolean,
): VimeoTextTrack | null {
  const candidates = allowAutoGenerated
    ? tracks
    : tracks.filter((track) => !isAutoGenerated(track));
  if (candidates.length === 0) {
    return null;
  }

  for (const lang of preferredLanguages) {
    const target = lang.toLowerCase();
    const matched = candidates.filter((track) => {
      const code = normalizeLang(track.lang);
      return code === target || code.startsWith(`${target}-`);
    });
    if (matched.length === 0) {
      continue;
    }
    return matched.find((track) => !isAutoGenerated(track)) ?? matched[0];
  }

  // 偏好语言都没命中，退回 default 轨道，其次第一条
  return (
    candidates.find((track) => track.default && !isAutoGenerated(track)) ??
    candidates.find((track) => !isAutoGenerated(track)) ??
    candidates[0]
  );
}

/**
 * 拉取并解析 vtt 字幕正文，失败时返回空数组。
 */
async function fetchTextTrack(
  track: VimeoTextTrack,
): Promise<VimeoSubtitleLine[]> {
  // 老配置里的 url 可能是相对路径，必须挂在 player.vimeo.com 下
  // （挂 vimeo.com 会吃 403，见 yt-dlp#12198）
  const url = track.url.startsWith('http')
    ? track.url
    : `https://player.vimeo.com${track.url}`;
  try {
    const res = await fetch(url);
    if (!res.ok) {
      defaultLogger.warn('[vimeo] texttrack request failed:', res.status);
      return [];
    }
    return parseVtt(await res.text());
  } catch (err) {
    defaultLogger.warn('[vimeo] texttrack request error:', err);
    return [];
  }
}

/**
 * 根据视频 ID 获取标题、作者与字幕。
 *
 * @param videoId 数字视频 ID，可先用 {@link parseVimeoVideoId} 从 URL 解析
 * @returns 配置拉取失败时返回 null；仅字幕缺失时 `subtitle` 为空数组
 */
async function getVimeoData(
  videoId: string,
  options: GetVimeoDataOptions = {},
): Promise<VimeoVideoData | null> {
  const {
    preferredLanguages = DEFAULT_PREFERRED_LANGUAGES,
    allowAutoGenerated = true,
    unlistedHash,
  } = options;

  const config = await fetchPlayerConfig(videoId, unlistedHash);
  if (!config?.video) {
    return null;
  }

  const tracks = config.request?.text_tracks ?? [];
  const picked = pickTrack(tracks, preferredLanguages, allowAutoGenerated);
  const subtitle = picked ? await fetchTextTrack(picked) : [];

  return {
    videoId: String(config.video.id),
    title: config.video.title,
    author: config.video.owner?.name ?? '',
    description: '',
    duration: config.video.duration || 0,
    subtitle,
    selectedTrack: picked && subtitle.length > 0 ? toTrackInfo(picked) : null,
    availableTracks: tracks.map(toTrackInfo),
  };
}

/**
 * Vimeo 视频页提取器。
 *
 * URL 是否为视频页由工厂函数判定，这里不再重复兜底。
 */
export class VimeoVideoExtractor extends AbstractContentExtractor {
  protected async doExtract(): Promise<ExtractResult> {
    const parsed = parseVimeoVideoId(this.url);
    if (!parsed) {
      return { text: '' };
    }

    const data = await getVimeoData(parsed.videoId, {
      unlistedHash: parsed.unlistedHash,
    });
    if (!data) {
      return { text: '' };
    }

    return {
      text: formatVideoMarkdown({
        title: data.title,
        author: data.author,
        description: data.description,
        duration: data.duration,
        url: this.url,
        subtitle: data.subtitle,
        selectedTrackLabel: data.selectedTrack?.label,
        availableTrackLabels: data.availableTracks.map((track) => track.label),
      }),
    };
  }
}
