/**
 * YouTube 视频页提取器，含字幕抓取逻辑（InnerTube 方案）。
 *
 * 与 B 站不同，YouTube 没有公开的字幕接口：
 * - 官方 Data API v3 的 `captions.download` 只有视频所有者能调用；
 * - 页面里的 `ytInitialPlayerResponse` 在 content script 的 isolated world 中读不到，
 *   且 YouTube 是 SPA，切视频后该对象不会更新。
 *
 * 因此这里走 InnerTube：POST `youtubei/v1/player` 按 videoId 现拉播放器数据，
 * 从中取出 `captionTracks`，再请求 timedtext 拿字幕正文。
 * 按当前 URL 的 videoId 现拉，也顺带解决了 SPA 切视频后数据过期的问题。
 *
 * 数据流：
 *   POST youtubei/v1/player { context, videoId }
 *     └─ .captions.playerCaptionsTracklistRenderer.captionTracks[]
 *          └─ GET {baseUrl}&fmt=json3
 *               └─ { events: [{ tStartMs, dDurationMs, segs: [{ utf8 }] }] }
 *
 * 注意：必须在 `youtube.com` 页面上下文中调用（content script），
 * 该接口依赖页面 cookie 与同源，脱离页面直接请求会拿到 `UNPLAYABLE`。
 */

import { defaultLogger } from '../../lib/logger';
import { ExtractResult } from '../interfaces';
import { AbstractContentExtractor } from './abstract.extractor';
import { formatVideoMarkdown } from './utils/video-markdown';

/** InnerTube WEB 客户端的公开 API key，YouTube 前端硬编码在页面里，非机密 */
const INNERTUBE_API_KEY = 'AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8';
/** 客户端版本号会随 YouTube 发版变化，过旧可能被拒；失败时优先怀疑这里 */
const INNERTUBE_CLIENT_VERSION_FALLBACK = '2.20240726.00.00';
const INNERTUBE_CLIENT_NAME = 'WEB';
/** `X-YouTube-Client-Name` 对应 WEB 客户端的数字编号 */
const INNERTUBE_CLIENT_NAME_ID = '1';
const PLAYER_ENDPOINT = 'https://www.youtube.com/youtubei/v1/player';
const CLIENT_VERSION_MARKERS = ['client.version\\x3d', 'client.version='];
const CLIENT_VERSION_PATTERN = /^[0-9]+(?:\.[0-9]+)+/;

/** `youtubei/v1/player` 返回体中用到的字段 */
interface InnertubePlayerResponse {
  playabilityStatus?: {
    /** `OK` / `LOGIN_REQUIRED` / `UNPLAYABLE` / `ERROR` 等 */
    status?: string;
    reason?: string;
  };
  videoDetails?: {
    videoId: string;
    title: string;
    author: string;
    shortDescription: string;
    lengthSeconds: string;
  };
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: InnertubeCaptionTrack[];
    };
  };
}

interface InnertubeCaptionTrack {
  /** timedtext 地址，已带签名参数；可能含 `exp=xpe`（见 PoToken 说明） */
  baseUrl: string;
  name?: { simpleText?: string; runs?: { text: string }[] };
  /** 形如 `en` / `zh-Hans` */
  languageCode: string;
  /** `asr` 表示自动生成字幕，人工字幕无此字段 */
  kind?: string;
  /** 形如 `.en`（人工）/ `a.en`（自动） */
  vssId?: string;
}

/** timedtext `fmt=json3` 的返回结构 */
interface TimedTextJson3 {
  events?: TimedTextEvent[];
}

interface TimedTextEvent {
  tStartMs?: number;
  dDurationMs?: number;
  /** 纯时序 / 样式标记事件没有 segs，需要过滤 */
  segs?: { utf8?: string }[];
}

/** 单条字幕。为便于与 B 站结果统一，`from`/`to` 用秒 */
interface YoutubeSubtitleLine {
  content: string;
  from: number;
  to: number;
}

/** 可选字幕轨道的描述信息 */
interface YoutubeSubtitleTrack {
  languageCode: string;
  /** 人类可读的语言名，如 `English (auto-generated)` */
  label: string;
  /** 是否为自动生成（ASR）字幕 */
  autoGenerated: boolean;
}

interface YoutubeVideoData {
  videoId: string;
  title: string;
  author: string;
  description: string;
  /** 视频时长（秒），拿不到时为 0 */
  duration: number;
  /** 选中轨道的字幕；无字幕或被 PoToken 拦截时为空数组 */
  subtitle: YoutubeSubtitleLine[];
  /** 实际选中的轨道，未取到字幕时为 null */
  selectedTrack: YoutubeSubtitleTrack | null;
  /** 该视频全部可用轨道，供调用方决定是否换一条重取 */
  availableTracks: YoutubeSubtitleTrack[];
}

interface GetYoutubeDataOptions {
  /**
   * 语言偏好，按顺序匹配，越靠前优先级越高。
   * 支持前缀匹配：`zh` 可命中 `zh-Hans` / `zh-Hant`。
   * 默认 `['zh-Hans', 'zh', 'en']`。
   */
  preferredLanguages?: string[];
  /**
   * 是否接受自动生成字幕（`kind === 'asr'`）。默认 true。
   * 为 true 时同语言仍优先选人工字幕。
   */
  allowAutoGenerated?: boolean;
}

const DEFAULT_PREFERRED_LANGUAGES = ['zh-Hans', 'zh', 'en'];

/**
 * 从 cookie 中提取指定名称的值。
 */
function getCookie(name: string): string | null {
  const value = `; ${document.cookie}`;
  const parts = value.split(`; ${name}=`);
  if (parts.length === 2) {
    return parts.pop()?.split(';').shift() ?? null;
  }
  return null;
}

/**
 * 生成 YouTube SAPISIDHASH Authorization header。
 * 用于已登录用户的身份验证，可以避免 LOGIN_REQUIRED 错误。
 *
 * @returns Authorization header 值，格式为 "SAPISIDHASH {timestamp}_{hash}"；
 *          未登录或无 SAPISID cookie 时返回 null
 */
async function generateSapisidHash(origin: string): Promise<string | null> {
  const sapisid = getCookie('SAPISID');
  if (!sapisid) {
    return null;
  }

  const timestamp = Math.floor(Date.now() / 1000);
  const message = `${timestamp} ${sapisid} ${origin}`;

  try {
    const encoder = new TextEncoder();
    const data = encoder.encode(message);
    const hashBuffer = await crypto.subtle.digest('SHA-1', data);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    const hashHex = hashArray
      .map((b) => b.toString(16).padStart(2, '0'))
      .join('');

    return `SAPISIDHASH ${timestamp}_${hashHex}`;
  } catch (err) {
    defaultLogger.warn('[youtube] failed to generate SAPISIDHASH:', err);
    return null;
  }
}

/**
 * 从页面内联脚本中提取 YouTube WEB 客户端版本号。
 *
 * content script 不能直接读页面脚本里的 `window.ytcfg`，只能从 DOM 侧解析。
 * 解析失败时返回 null，由调用方使用兜底版本。
 */
export function readInnertubeClientVersion(): string | null {
  for (const script of Array.from(document.scripts)) {
    const text = script.textContent ?? '';
    if (!text.includes('client.version')) {
      continue;
    }

    for (const marker of CLIENT_VERSION_MARKERS) {
      const index = text.indexOf(marker);
      if (index === -1) {
        continue;
      }

      const matched = text
        .slice(index + marker.length)
        .match(CLIENT_VERSION_PATTERN);
      if (matched?.[0]) {
        return matched[0];
      }
    }
  }

  return null;
}

/**
 * 从 URL 中解析 videoId，兼容 `watch?v=` / `youtu.be/` / `/shorts/` / `/embed/`。
 *
 * @returns 解析失败返回 null
 */
function parseYoutubeVideoId(rawUrl: string): string | null {
  let url: URL;
  try {
    url = new URL(rawUrl);
  } catch {
    return null;
  }

  if (url.hostname === 'youtu.be') {
    const id = url.pathname.slice(1).split('/')[0];
    return id || null;
  }

  if (!/(^|\.)youtube(-nocookie)?\.com$/.test(url.hostname)) {
    return null;
  }

  const v = url.searchParams.get('v');
  if (v) {
    return v;
  }

  const match = /^\/(?:shorts|embed|live|v)\/([^/?#]+)/.exec(url.pathname);
  return match?.[1] ?? null;
}

/**
 * 调用 InnerTube player 接口拿播放器数据。
 */
async function fetchPlayerResponse(
  videoId: string,
): Promise<InnertubePlayerResponse | null> {
  try {
    const clientVersion =
      readInnertubeClientVersion() ?? INNERTUBE_CLIENT_VERSION_FALLBACK;
    const origin = 'https://www.youtube.com';

    // 生成 SAPISIDHASH Authorization header（用于已登录用户）
    const authorization = await generateSapisidHash(origin);

    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
      Origin: origin,
      Referer: `${origin}/watch?v=${videoId}`,
      'X-YouTube-Client-Name': INNERTUBE_CLIENT_NAME_ID,
      'X-YouTube-Client-Version': clientVersion,
    };

    // 如果成功生成 Authorization header，添加到请求中
    if (authorization) {
      headers.Authorization = authorization;
    }

    const res = await fetch(
      `${PLAYER_ENDPOINT}?key=${INNERTUBE_API_KEY}&prettyPrint=false`,
      {
        method: 'POST',
        credentials: 'include',
        headers,
        body: JSON.stringify({
          videoId,
          context: {
            client: {
              clientName: INNERTUBE_CLIENT_NAME,
              clientVersion,
              hl: 'zh-CN',
              gl: 'CN',
            },
          },
          // 跳过播放前贴片等无关数据，减小响应体
          contentCheckOk: true,
          racyCheckOk: true,
        }),
      },
    );
    if (!res.ok) {
      defaultLogger.warn('[youtube] player request failed:', res.status);
      return null;
    }
    return (await res.json()) as InnertubePlayerResponse;
  } catch (err) {
    defaultLogger.warn('[youtube] player request error:', err);
    return null;
  }
}

/**
 * 取轨道的可读名称，InnerTube 有 `simpleText` 和 `runs` 两种形态。
 */
function readTrackLabel(track: InnertubeCaptionTrack): string {
  const { name } = track;
  if (name?.simpleText) {
    return name.simpleText;
  }
  const fromRuns = name?.runs?.map((run) => run.text).join('');
  return fromRuns || track.languageCode;
}

function toTrackInfo(track: InnertubeCaptionTrack): YoutubeSubtitleTrack {
  return {
    languageCode: track.languageCode,
    label: readTrackLabel(track),
    autoGenerated: track.kind === 'asr',
  };
}

/**
 * 按语言偏好挑一条轨道。同一语言下人工字幕优先于自动生成字幕。
 *
 * @returns 没有任何可用轨道时返回 null
 */
function pickTrack(
  tracks: InnertubeCaptionTrack[],
  preferredLanguages: string[],
  allowAutoGenerated: boolean,
): InnertubeCaptionTrack | null {
  const candidates = allowAutoGenerated
    ? tracks
    : tracks.filter((track) => track.kind !== 'asr');
  if (candidates.length === 0) {
    return null;
  }

  for (const lang of preferredLanguages) {
    const target = lang.toLowerCase();
    const matched = candidates.filter((track) => {
      const code = track.languageCode.toLowerCase();
      // 前缀匹配让 `zh` 能命中 `zh-Hans` / `zh-Hant`
      return code === target || code.startsWith(`${target}-`);
    });
    if (matched.length === 0) {
      continue;
    }
    // 同语言优先人工字幕
    return matched.find((track) => track.kind !== 'asr') ?? matched[0];
  }

  // 偏好语言都没命中，退回第一条（同样优先人工）
  return candidates.find((track) => track.kind !== 'asr') ?? candidates[0];
}

/**
 * 拉取并解析 timedtext 字幕正文。
 *
 * PoToken 说明：部分视频的 baseUrl 带 `exp=xpe`，缺少 `pot` 参数时接口会返回
 * **HTTP 200 但空 body**。这里把这种情况按「无字幕」处理并记日志，
 * 不能当成成功，否则下游会拿到静默的空结果。
 */
async function fetchTimedText(baseUrl: string): Promise<YoutubeSubtitleLine[]> {
  const url = `${baseUrl}&fmt=json3`;
  try {
    const res = await fetch(url, { credentials: 'include' });
    if (!res.ok) {
      return [];
    }
    const raw = await res.text();
    if (!raw.trim()) {
      defaultLogger.warn(
        '[youtube] timedtext returned empty body, likely PoToken required (exp=xpe)',
      );
      return [];
    }

    const json = JSON.parse(raw) as TimedTextJson3;
    return (json.events ?? [])
      .map((event) => {
        // 没有 segs 的是时序 / 样式标记事件，直接丢弃
        if (!event.segs) {
          return null;
        }
        const content = event.segs
          .map((seg) => seg.utf8 ?? '')
          .join('')
          .replace(/\s+/g, ' ')
          .trim();
        if (!content) {
          return null;
        }
        // YouTube 给的是毫秒，统一换算成秒，与 B 站字幕结构对齐
        const start = (event.tStartMs ?? 0) / 1000;
        const end = start + (event.dDurationMs ?? 0) / 1000;
        return { content, from: start, to: end };
      })
      .filter((line): line is YoutubeSubtitleLine => line !== null);
  } catch (err) {
    defaultLogger.warn('[youtube] timedtext request error:', err);
    return [];
  }
}

/**
 * 根据 videoId 获取视频标题、作者、简介与字幕。
 *
 * 必须在 `youtube.com` 页面上下文中调用（content script），
 * 依赖同源与页面 cookie。
 *
 * @param videoId 视频 ID，如 `dQw4w9WgXcQ`；也可先用 {@link parseYoutubeVideoId} 从 URL 解析
 * @returns 接口失败或视频不可播放时返回 null；仅字幕缺失时 `subtitle` 为空数组
 */
export async function getYoutubeData(
  videoId: string,
  options: GetYoutubeDataOptions = {},
): Promise<YoutubeVideoData | null> {
  const {
    preferredLanguages = DEFAULT_PREFERRED_LANGUAGES,
    allowAutoGenerated = true,
  } = options;

  const player = await fetchPlayerResponse(videoId);
  if (!player) {
    return null;
  }

  const status = player.playabilityStatus?.status;
  if (status && status !== 'OK') {
    // 业务层提示不可播放时，仍尽量保留已拿到的 videoDetails / 描述信息
    defaultLogger.warn(
      '[youtube] video not playable:',
      status,
      player.playabilityStatus?.reason,
    );
  }

  const details = player.videoDetails;
  if (!details) {
    return null;
  }

  const tracks =
    player.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
  const availableTracks = tracks.map(toTrackInfo);

  const picked = pickTrack(tracks, preferredLanguages, allowAutoGenerated);
  const subtitle = picked ? await fetchTimedText(picked.baseUrl) : [];

  return {
    videoId: details.videoId,
    title: details.title,
    author: details.author,
    description: details.shortDescription,
    duration: Number.parseInt(details.lengthSeconds, 10) || 0,
    subtitle,
    // 字幕实际没取到时不谎报 selectedTrack
    selectedTrack: picked && subtitle.length > 0 ? toTrackInfo(picked) : null,
    availableTracks,
  };
}

/**
 * YouTube 视频页提取器。
 *
 * URL 是否为视频页由工厂函数判定，这里不再重复兜底。
 */
export class YoutubeVideoExtractor extends AbstractContentExtractor {
  protected async doExtract(): Promise<ExtractResult> {
    const videoId = parseYoutubeVideoId(this.url);
    if (!videoId) {
      return { text: '' };
    }

    const data = await getYoutubeData(videoId);
    if (!data) {
      return { text: '' };
    }

    return {
      text: formatVideoMarkdown({
        title: data.title,
        author: data.author,
        description: data.description,
        duration: data.duration,
        url: this.url,
        subtitle: data.subtitle,
        selectedTrackLabel: data.selectedTrack?.label,
        availableTrackLabels: data.availableTracks.map((track) => track.label),
      }),
    };
  }
}
